import { addDaysIso, todayIso } from "@/lib/date-utils";
import type {
  CollectionItem,
  CrawlRun,
  CrawlSource,
  EventSuggestion,
  Franchise,
  OtakuEvent,
  Reminder,
} from "@/lib/types";

const today = todayIso();

export const demoFranchises: Franchise[] = [
  {
    id: "fr-blue-archive",
    name: "블루 아카이브",
    slug: "blue-archive",
    category: "game",
    colorCode: "#2563EB",
    priority: 1,
  },
  {
    id: "fr-genshin",
    name: "원신",
    slug: "genshin",
    category: "game",
    colorCode: "#0EA5E9",
    priority: 1,
  },
  {
    id: "fr-arknights",
    name: "명일방주",
    slug: "arknights",
    category: "game",
    colorCode: "#F59E0B",
    priority: 2,
  },
  {
    id: "fr-project-sekai",
    name: "프로젝트 세카이",
    slug: "project-sekai",
    category: "game",
    colorCode: "#EC4899",
    priority: 2,
  },
  {
    id: "fr-hololive",
    name: "홀로라이브",
    slug: "hololive",
    category: "vtuber",
    colorCode: "#34D399",
    priority: 3,
  },
];

export const demoEvents: OtakuEvent[] = [
  {
    id: "ev-cafe-1",
    franchiseId: "fr-blue-archive",
    type: "cafe",
    title: "블루 아카이브 콜라보 카페 2차 예약 오픈",
    startDate: addDaysIso(today, 1),
    endDate: addDaysIso(today, 21),
    location: "서울 홍대",
    sourceUrl: "https://example.com/blue-archive-cafe",
    isVerified: true,
    createdAt: new Date().toISOString(),
    saved: true,
    remindDays: [3, 7],
  },
  {
    id: "ev-genshin-1",
    franchiseId: "fr-genshin",
    type: "preorder",
    title: "원신 신규 캐릭터 픽업 시작",
    startDate: addDaysIso(today, 3),
    endDate: addDaysIso(today, 24),
    location: "온라인",
    sourceUrl: "https://example.com/genshin-pickup",
    isVerified: true,
    createdAt: new Date().toISOString(),
    saved: true,
    remindDays: [1, 3],
  },
  {
    id: "ev-arknights-1",
    franchiseId: "fr-arknights",
    type: "popup",
    title: "명일방주 리턴 투 미스트 팝업 스토어",
    startDate: addDaysIso(today, 8),
    endDate: addDaysIso(today, 15),
    location: "더현대 서울",
    sourceUrl: "https://example.com/arknights-popup",
    isVerified: true,
    createdAt: new Date().toISOString(),
    saved: true,
  },
  {
    id: "ev-stream-1",
    franchiseId: "fr-hololive",
    type: "broadcast",
    title: "홀로라이브 한국어 공식 방송",
    startDate: addDaysIso(today, 6),
    sourceUrl: "https://example.com/hololive-stream",
    isVerified: true,
    createdAt: new Date().toISOString(),
    saved: false,
  },
];

export const demoCollections: CollectionItem[] = [
  {
    id: "col-1",
    eventId: "ev-genshin-1",
    franchiseId: "fr-genshin",
    itemName: "원신 4주년 한정 아크릴 스탠드 세트",
    price: 120000,
    isWishlist: true,
    memo: "예약 시작일에 바로 확인",
  },
  {
    id: "col-2",
    eventId: "ev-cafe-1",
    franchiseId: "fr-blue-archive",
    itemName: "아로나 1/7 스케일 피규어",
    price: 188000,
    isWishlist: true,
    memo: "2026년 9월 발매 예정",
  },
  {
    id: "col-3",
    eventId: "ev-cafe-1",
    franchiseId: "fr-blue-archive",
    itemName: "콜라보 카페 한정 코스터 3종",
    price: 22000,
    isWishlist: false,
    boughtAt: today,
    memo: "카페 방문 때 구매 완료",
  },
  {
    id: "col-4",
    eventId: "ev-arknights-1",
    franchiseId: "fr-arknights",
    itemName: "케르시 닥터 한정 굿즈 세트",
    price: 85000,
    isWishlist: false,
    boughtAt: today,
    memo: "팝업 현장 수령",
  },
];

export const demoSources: CrawlSource[] = [
  {
    id: "source-naver",
    franchiseId: "fr-blue-archive",
    sourceType: "naver_lounge",
    name: "네이버 라운지 공지",
    url: "https://example.com/naver-lounge",
    keywords: ["콜라보", "카페", "예약", "굿즈"],
    isActive: true,
    lastCrawledAt: new Date().toISOString(),
  },
  {
    id: "source-dc",
    franchiseId: "fr-genshin",
    sourceType: "dc",
    name: "원신 커뮤니티 게시판",
    url: "https://example.com/dc-gallery",
    keywords: ["발매", "예약", "픽업"],
    isActive: true,
    lastCrawledAt: new Date().toISOString(),
  },
  {
    id: "source-official",
    franchiseId: "fr-arknights",
    sourceType: "official",
    name: "공식 소식 페이지",
    url: "https://example.com/official-news",
    keywords: ["이벤트", "팝업", "굿즈"],
    isActive: true,
    lastCrawledAt: null,
  },
];

export const demoSuggestions: EventSuggestion[] = [
  {
    id: "sg-1",
    crawledPostId: "post-1",
    franchiseId: "fr-blue-archive",
    title: "블루 아카이브 팝업 스토어 오픈",
    eventType: "popup",
    startDate: addDaysIso(today, 10),
    endDate: addDaysIso(today, 17),
    location: "더현대 서울",
    sourceUrl: "https://example.com/post/1",
    confidence: 0.86,
    warnings: ["운영 종료일은 본문에서 추정됨"],
    status: "pending",
    createdAt: new Date().toISOString(),
  },
  {
    id: "sg-2",
    crawledPostId: "post-2",
    franchiseId: "fr-genshin",
    title: "원신 신규 5성 캐릭터 픽업 일정",
    eventType: "preorder",
    startDate: addDaysIso(today, 4),
    endDate: addDaysIso(today, 25),
    location: "온라인",
    sourceUrl: "https://example.com/post/2",
    confidence: 0.94,
    warnings: [],
    status: "pending",
    createdAt: new Date().toISOString(),
  },
  {
    id: "sg-3",
    crawledPostId: "post-3",
    franchiseId: "fr-arknights",
    title: "명일방주 신규 이벤트 리턴 투 미스트",
    eventType: "goods_release",
    startDate: addDaysIso(today, 12),
    endDate: addDaysIso(today, 28),
    location: "온라인",
    sourceUrl: "https://example.com/post/3",
    confidence: 0.78,
    warnings: ["굿즈 발매 여부는 후속 공지 확인 필요"],
    status: "pending",
    createdAt: new Date().toISOString(),
  },
];

export const demoReminders: Reminder[] = [
  {
    id: "rem-1",
    eventId: "ev-cafe-1",
    remindAt: `${today}T09:00:00.000Z`,
    status: "pending",
  },
];

export const demoCrawlRuns: CrawlRun[] = [
  {
    id: "run-1",
    sourceId: "source-naver",
    status: "success",
    postsFound: 8,
    suggestionsCreated: 1,
    startedAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    finishedAt: new Date(Date.now() - 1000 * 60 * 28).toISOString(),
  },
  {
    id: "run-2",
    sourceId: "source-dc",
    status: "success",
    postsFound: 12,
    suggestionsCreated: 2,
    startedAt: new Date(Date.now() - 1000 * 60 * 90).toISOString(),
    finishedAt: new Date(Date.now() - 1000 * 60 * 87).toISOString(),
  },
];
